namespace ITEJA_CustomLanguage.Lexer
{
    /// <summary>
    /// The main part of the lexer, these tokens
    /// are generated by all words in the source code
    /// </summary>
    public class Token
    {
        /// <summary>
        /// Type of the token that will be used
        /// by parser to determine what class to create
        /// </summary>
        public TokenType Type { get; set; }
        /// <summary>
        /// Value of the token that will be used to fill
        /// in parameters of the classes.
        /// </summary>
        public string Value { get; set; }
    }
}
